import { FRAMEWORK_TEMPLATES, RHCA_CORE } from "./config.js";
import { getState, mutate, recordEvent } from "./state.js";
import { exportFramework } from "./services.js";

const esc = v => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const blankCriterion = () => ({ name:"New domain criterion", relationship:"A", definition:"", evidence:"", anchors:{1:"",2:"",3:""}, tags:"" });
const checks = c => [c.name.trim().length>=5, RHCA_CORE[c.relationship], c.definition.trim().length>=40, c.evidence.trim().length>=40, Object.values(c.anchors).every(x=>x.trim().length>=35), c.tags.trim().length>=3];

export function renderFramework(root) {
  const s=getState(), fw=s.framework, i=Math.min(fw.activeCriterionIndex,fw.criteria.length-1), c=fw.criteria[i];
  const quality=checks(c), passed=quality.filter(Boolean).length;
  root.innerHTML=`<div class="page"><header class="page-header"><div><span class="eyebrow">Task 2 · configuration-driven framework</span><h1>Build a multi-dimensional domain framework</h1><p>RHCA remains stable. Add multiple observable domain criteria and map each one to R, H, C, or A.</p></div><div class="header-actions"><button id="addCriterion" class="button secondary">+ Add criterion</button><button id="exportFramework" class="button secondary">Export</button><button id="completeFramework" class="button success">Complete task</button></div></header>
  <div class="framework-shell"><aside class="framework-sidebar"><label class="stacked-label">Domain template<select id="templateSelect">${Object.entries(FRAMEWORK_TEMPLATES).map(([id,t])=>`<option value="${id}" ${fw.template===id?"selected":""}>${esc(t.name)}</option>`).join("")}</select></label><label class="stacked-label">Framework name<input id="frameworkName" value="${esc(fw.name)}"></label><h2>Criteria (${fw.criteria.length})</h2><div class="criterion-list">${fw.criteria.map((x,n)=>`<button class="criterion-tab ${n===i?"active":""}" data-criterion="${n}"><b>${esc(x.name)}</b><small>${x.relationship} · ${esc(RHCA_CORE[x.relationship].name)}</small></button>`).join("")}</div><div class="notice"><b>Stable core:</b> criteria may extend RHCA, but cannot rename or remove its four constructs.</div></aside>
  <section class="framework-editor"><div class="section-title"><h2>Criterion ${i+1}</h2><span><button id="duplicateCriterion" class="text-button">Duplicate</button> <button id="deleteCriterion" class="text-button">Delete</button></span></div><div class="two-fields"><label>Criterion name<input id="criterionName" value="${esc(c.name)}"></label><label>RHCA parent<select id="criterionRelationship">${Object.entries(RHCA_CORE).map(([k,d])=>`<option value="${k}" ${c.relationship===k?"selected":""}>${k} · ${esc(d.name)}</option>`).join("")}</select></label></div><label>Observable construct<textarea id="criterionDefinition">${esc(c.definition)}</textarea></label><label>Evidence rule<textarea id="criterionEvidence">${esc(c.evidence)}</textarea></label><h2>Anchored ratings</h2><div class="anchor-grid">${[1,2,3].map(n=>`<label><span class="score-box">${n}</span><textarea data-anchor="${n}">${esc(c.anchors[n])}</textarea></label>`).join("")}</div><label class="failure-tags-field">Domain failure tags<textarea id="criterionTags" rows="5" placeholder="Enter multiple tags separated by commas, e.g., oversimplification, missing prerequisite, unexplained jargon">${esc(c.tags)}</textarea><small>Add as many tags as needed. Separate tags with commas.</small></label></section>
  <aside class="quality-panel"><div class="quality-score"><span>Current criterion</span><b>${passed}/6</b><div class="progress-bar"><i style="width:${passed/6*100}%"></i></div></div>${["Specific name","RHCA mapping","Observable definition","Evidence rule","Distinct anchors","Failure tags"].map((x,n)=>`<div class="quality-check ${quality[n]?"pass":"fail"}"><b>${quality[n]?"✓":"!"}</b><span>${x}</span></div>`).join("")}<div class="preview-card"><pre>${esc(JSON.stringify({criteria:fw.criteria.map(x=>({name:x.name,parent:x.relationship}))},null,2))}</pre></div></aside></div></div>`;
  bind(root,i);
}

function bind(root,i){
 const rerender=()=>renderFramework(root); const edit=(field,value)=>mutate(s=>{s.framework.criteria[i][field]=value;s.framework.status="draft";},"framework.criterion_edited",{index:i,field});
 root.querySelectorAll("[data-criterion]").forEach(b=>b.onclick=()=>{mutate(s=>s.framework.activeCriterionIndex=Number(b.dataset.criterion),"framework.criterion_selected");rerender();});
 root.querySelector("#addCriterion").onclick=()=>{mutate(s=>{s.framework.criteria.push(blankCriterion());s.framework.activeCriterionIndex=s.framework.criteria.length-1;s.completed.framework=false;},"framework.criterion_added");rerender();};
 root.querySelector("#duplicateCriterion").onclick=()=>{mutate(s=>{const copy=structuredClone(s.framework.criteria[i]);copy.name+=` copy`;s.framework.criteria.splice(i+1,0,copy);s.framework.activeCriterionIndex=i+1;},"framework.criterion_duplicated");rerender();};
 root.querySelector("#deleteCriterion").onclick=()=>{if(getState().framework.criteria.length===1)return alert("A framework needs at least one criterion.");mutate(s=>{s.framework.criteria.splice(i,1);s.framework.activeCriterionIndex=Math.max(0,i-1);},"framework.criterion_deleted");rerender();};
 root.querySelector("#templateSelect").onchange=e=>{mutate(s=>{const t=FRAMEWORK_TEMPLATES[e.target.value];s.framework.template=e.target.value;s.framework.name=`${t.name} Framework`;s.framework.domain=t.domain;s.framework.criteria=t.examples.length?structuredClone(t.examples):[blankCriterion()];s.framework.activeCriterionIndex=0;},"framework.template_selected");rerender();};
 root.querySelector("#frameworkName").oninput=e=>mutate(s=>s.framework.name=e.target.value,"framework.name_edited");
 [["criterionName","name"],["criterionRelationship","relationship"],["criterionDefinition","definition"],["criterionEvidence","evidence"],["criterionTags","tags"]].forEach(([id,f])=>{root.querySelector(`#${id}`).onchange=e=>{edit(f,e.target.value);rerender();};});
 root.querySelectorAll("[data-anchor]").forEach(a=>a.onchange=e=>{mutate(s=>s.framework.criteria[i].anchors[e.target.dataset.anchor]=e.target.value,"framework.anchor_edited");rerender();});
 root.querySelector("#exportFramework").onclick=exportFramework;
 root.querySelector("#completeFramework").onclick=()=>{const all=getState().framework.criteria.every(c=>checks(c).every(Boolean));if(!all)return alert("Every criterion must pass all six quality checks.");mutate(s=>{s.framework.status="ready for pilot";s.completed.framework=true;},"task.framework_completed",{criteria:getState().framework.criteria.length});rerender();};
 recordEvent("view.framework_opened",{criterionIndex:i});
}
